### ISSUE TITLE
[Feature] - Update Strategy "updateData"

### ISSUE THREAD

**Issue by vueda** [angeliski/vue-tabulator#13]
When trying to navigate through editable cells using the tab key the focus always returns to the first editable cell (if the cell data has been changed). 
This happens using both DATA and REPLACE strategy.

The expected behavior is to focus the next editable cell on tab key press.

The addition of a new data update strategy using Tabulator's updateData can solve this.

Here is a JSFiddle that shows the expected behavior. You can simulate the other scenarios changing de method used inside the cellEdited callback.

https://jsfiddle.net/gfnu2jbw/

**Comment by angeliski** [comment]
Release version 1.1.0 using the `UPDATE` strategy.
I will keep that issue opened to think about use that strategy in default mode when a editable table be created.

Thanks for issue and for PR
