### ISSUE TITLE
[BUG] - Typo with one of the cell events (cellTapHOld -> cellTapHold)

### ISSUE THREAD

**Issue by aledujke** [angeliski/vue-tabulator#24]
I am sorry for not following the template but the bug seems to be quite minor. I can submit a PR later today.

Inside of the file: `src/feature/events/cell-events.ts` one of the events is called `cellTapHOld` instead of `cellTapHold`. I noticed it because I am getting warnings since updating to "version": "1.2.0", of Vue-tabulator

**Comment by angeliski** [comment]
Nice @aledujke 
I will fix that soon as possible

Thank you for the issue

**Comment by angeliski** [comment]
Release version 1.2.1 fix that.
See you.
