### ISSUE TITLE
Do not recreate the entire grid on data changes

### ISSUE THREAD

**Issue by morficus** [angeliski/vue-tabulator#3]
With the current implementation, every time the `tableData` updates (aka: v-model) the component destroys the current Tabulator instance and creates a complete new one. Doing so could create performance issues with tables that update data frequently.

Instead the component should internally be using `tabulatorInstance.setData() or `tabulatorInstance.replaceData()` to recycle the already existing Tabulator instance.

ref1: http://tabulator.info/docs/4.2/data#array
ref2: http://tabulator.info/docs/4.2/update#alter-replace

**Comment by angeliski** [comment]
Make senses @morficus .
I will work in that.

**Comment by angeliski** [comment]
Hey @morficus I made a PR to change that.
You can see the #4  and the new [docs](https://deploy-preview-4--vue-tabulator.netlify.com/guide/#updatestrategy)

I will merge that in the monday and generate a new rc.

**Comment by angeliski** [comment]
New rc version published. 
Thank's for the report
