### ISSUE TITLE
[BUG] - table.getData() "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by rigogsilva** [angeliski/vue-tabulator#31]
**Description**
I am trying to get the data from the tabular table after it is all rendered. But using the following code: 

```javascript
function getData() {
  const table = this.$refs.tabulator.getInstance();
  console.log('get data');
  const data = table.getData();
  console.log(data);
}
```

The function `table.getData();` fails with the following error:
```console
[Vue warn]: Error in mounted hook: "RangeError: Maximum call stack size exceeded"

found in

---> <FinancePanel>
       <AccountView> at src/views/AccountView/AccountView.vue
         <App> at src/App.vue
           <Root>
RangeError: Maximum call stack size exceeded
    at Object.deepClone (tabulator.js?39ab:9480)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
```

**Tabulator Info**
- tabulator-table: 4.4.3
- Also using vue-tabulator: 1.2.2
```pug
      TabulatorComponent.table-sm.table-striped(
        v-model="tableSettings.data" :options="tableSettings.options" ref="tabulator"
      )
```

**Screenshots**
![image](https://user-images.githubusercontent.com/31558765/66859896-c059a280-ef51-11e9-8e32-9a51a0619602.png)

**Desktop (please complete the following information):**
 - Google Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by angeliski** [comment]
Hey @rigogsilva  I tried get the error but nothing wrong happening

You can see here : https://jsfiddle.net/angeliski/z8wbvr10/

Can you try change that fiddle to your use case?

See you
Rogerio

**Comment by rigogsilva** [comment]
Hey Rogerio,

Maybe it is the environment? I am using it with vue 3.0 (which uses webpack). 

Also this is how I am using the component. Let me know if you see anything wrong: 

```javascript
import { TabulatorComponent } from 'vue-tabulator';
```

```pug
      TabulatorComponent.table-sm.table-striped(
        v-if="!exporting"
        v-model="data"
        :options="options"
        ref="tabulator"
      )
```

**Comment by rigogsilva** [comment]
Ok, I added the simple data you posted and options on the same environment. That worked just fine. It must be the data or the complicated `options` formatting I am doing for some of the columns like `Amount`, `Plan Id`, or `Description`.

**Comment by angeliski** [comment]
Hey @rigogsilva I will close that issue for now, any problem you can open another 
Sorry the delay
