### ISSUE TITLE
[BUG] - Vue-Tabulator don't remove old column, if I install new options.

### ISSUE THREAD

**Issue by aalopatin** [angeliski/vue-tabulator#44]
Hi!

I try to change a set of columns in the options of the tabulator.
When I add new columns it works, but when I remove column from options, they aren't removed.

Here is part of my code.

I have a method - setPeriods(), which set columns in the options object.

```
setPeriods() {
    let length = this.optionsDataReports.columns.length
    let columnsPeriods = this.selectedPeriods.map((period) => {
      return COLUMNS_ENTER_REPORTS.columnPeriod(period.id, period.id)
    })
    this.optionsDataReports.columns.splice(1, length-1, ...columnsPeriods)
},
```

If new Periods are added in selectedPeriods it work correct:
![AddColumns](https://user-images.githubusercontent.com/52285445/68865005-20836600-0703-11ea-9dd0-bd22da54bba0.PNG)

But if I delete columns, tabulator instance isn't updated:
![DeleteColumns](https://user-images.githubusercontent.com/52285445/68865078-3db83480-0703-11ea-879d-fb4ed5720347.png)

But the options object is updated in Vue:
![OptionsAfterDeleteColumns](https://user-images.githubusercontent.com/52285445/68865127-51fc3180-0703-11ea-9393-c289c3799f85.png)

I can't solve this problem. Can you help me?

**Comment by aalopatin** [comment]
I don't know if it's Vue-tabulator or Tabulator problem.

**Comment by angeliski** [comment]
Hey @aalopatin 
Can you try reproduce that behavior in fork fiddle? https://jsfiddle.net/angeliski/z8wbvr10/

**Comment by aalopatin** [comment]
Hey @angeliski 
I add buttons Add and Remove

Add - adds **2 columns** to replace everything after the second column
Remove - adds **1 column** to replace everything after the second column

If click Remove and then Add it works
But if click Add and then Remove it doesn't work

 https://jsfiddle.net/utqr2ywh/3/

**Comment by angeliski** [comment]
Thanks @aalopatin 

I will try find the bug

**Comment by BryceBarbara** [comment]
@angeliski It looks like the bug is in this line: https://github.com/angeliski/vue-tabulator/blob/dev/src/components/TabulatorComponent.vue#L58

instead of 
```js
...mergeWith(this.eventOptions, this.options, merge),
```
try doing
```js
...mergeWith({}, this.eventOptions, this.options, merge),
```

**Comment by angeliski** [comment]
Hey @BryceBarbara Thanks for the advice
I will try to get that
