### ISSUE TITLE
Vue Tabulator: Change Cell Color

### ISSUE THREAD

**Issue by leokyohan** [angeliski/vue-tabulator#76]
Is there a feature in vue tabulator to change cell color based on the input data in that field?
I have seen row-formatter in Tabulator. But couldn't see any feature like that in vue tabulator. Also I couldn't figure out how to implement that in vue-tabulator.

It would be really good if you can give an interim solution also, if the feature is not present currently.

**Comment by angeliski** [comment]
Hey @leokyohan Sorry the delay.

You can use any feature how has in Tabulator, using the [Options](https://vue-tabulator.netlify.app/guide/#options) or maybe using an [advanced interaction](https://vue-tabulator.netlify.app/guide/#advanced-interaction)

That could help?

**Comment by leokyohan** [comment]
Okay great. I'll try this out. I just wanted to know if VueTabulator has a way of doing this, without calling the tabulator instance.
Thanks for the reply.
