### ISSUE TITLE
[Feature] Vue 3 support

### ISSUE THREAD

**Issue by leifcr** [angeliski/vue-tabulator#95]
Is there a plan for Vue 3 support?

**Comment by angeliski** [comment]
Hey @leifcr 
We can provide support to Vue 3, but I am not working on that.

Do you have any specific requirements for that?

**Comment by leifcr** [comment]
@angeliski it was just a question, as I was drafting up a project here. Did a quick test using the composition api, and I think with the new composition API it's just as easy to just use tabulator directly. 

The only thing that seems broken for this to work with Vue 3 is the events. I'll close this, as the composition api makes it just as easy to use it directly.

**Comment by Heran-foo** [comment]
@leifcr I was also trying to use tabulator directly in my Vue3 project but the table does not render as it is shown in examples (tabulator docs) so if you could provide some hint or idea as you have already got some idea to work around with vue3. Thankyou and your help will be appreciated.

**Comment by leifcr** [comment]
@Heran2019 Example implementation of tabulator in a component. I use vue-class-component, so the syntax is a bit different from 'plain vue'

```vue
<template>
  <div
    ref="table"
    class="tabulator"
  />
</template>

<script lang="ts">
import mergeWith from 'lodash.mergewith';
import Tabulator from 'tabulator-tables';
import '@/styles/tabulator_midnight_compact.css';
import { Options, mixins } from 'vue-class-component';


@Options({
  props: {
    tabdata: TabulatorData,
  },
  components: {
    // VueTabulator
  }
})

export default class MyTabulatorEditor extends mixins(useLogger) {
  tabdata!: TabulatorData,
  options!: Tabulator.Options
  private tabulatorInstance!: Tabulator | null;

  getSettings() :TabulatorData {
    return this.tabdata;
  }

  getTabulatorInstance() : Tabulator | null {
    return this.tabulatorInstance;
  }

  created() : void {
    this.options = {
      layout:'fitDataStretch', //fit columns to width of table (optional)
      reactiveData: true,
      headerSort: false,
      columns:[ //Define Table Columns
        { title:'Field', field:'name' },
        { title:'Value', field:'value' },
        { title:'Start', field:'start' },
        { title: 'Comment', field: 'comment', minWidth: 300, hozAlign: 'left', editor: 'input' }
      ]
    }
  }
  private createTable() {
    if (this.tabdata == null || this.tabdata == undefined) {
      console.log('Editor: Data missing!');
      return;
    }
    let resolvedOptions = {
      ...mergeWith({}, this.options),
      data: this.settings.data,
    };

    this.tabulatorInstance = new Tabulator(
      (this.$refs.table as HTMLElement),
      resolvedOptions
    );
  }

  mounted() : void {
    this.createTable();
  }
}

</script>
<style>
</style>
```

You can extract the methods into a composition api, and include that in your component instead, but it depeneds on how reusable you need the table to be.

**Comment by Heran-foo** [comment]
@leifcr thank you, I will try and let you know if I face any problem.
